/**
 *@Generated by sagacity-quickvo 5.0
 */
package com.strict.modules.system.entity;

import java.io.Serializable;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;
import org.sagacity.sqltoy.config.annotation.Column;
import lombok.Data;
import lombok.experimental.Accessors;
import java.time.LocalDateTime;

/**
 * @project sqltoy-strict
 * @version 1.0.0
 * Table: sys_organ_info,Remark:机构信息表  
 */
@Data
@Accessors(chain = true)
@Entity(tableName="sys_organ_info",pk_constraint="PRIMARY")
public class OrganInfo implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 484724793842815100L;
/*---begin-auto-generate-don't-update-this-area--*/	
	/**
	 * jdbcType:VARCHAR
	 */
	@Id(strategy="generator",generator="org.sagacity.sqltoy.plugins.id.impl.DefaultIdGenerator")
	@Column(name="ORGAN_ID",comment="机构ID",length=22L,type=java.sql.Types.VARCHAR,nullable=false)
	private String organId;
	
	/**
	 * jdbcType:VARCHAR
	 */
	@Column(name="ORGAN_NAME",comment="机构名称",length=100L,type=java.sql.Types.VARCHAR,nullable=false)
	private String organName;
	
	/**
	 * jdbcType:VARCHAR
	 */
	@Column(name="ORGAN_CODE",comment="机构代码",length=20L,type=java.sql.Types.VARCHAR,nullable=false)
	private String organCode;
	
	/**
	 * jdbcType:VARCHAR
	 */
	@Column(name="COST_NO",comment="成本中心代码",length=20L,type=java.sql.Types.VARCHAR,nullable=true)
	private String costNo;
	
	/**
	 * jdbcType:VARCHAR
	 */
	@Column(name="ORGAN_PID",comment="父机构ID",length=22L,type=java.sql.Types.VARCHAR,nullable=false)
	private String organPid;
	
	/**
	 * jdbcType:VARCHAR
	 */
	@Column(name="NODE_ROUTE",comment="节点路径",length=200L,type=java.sql.Types.VARCHAR,nullable=true)
	private String nodeRoute;
	
	/**
	 * jdbcType:DECIMAL
	 */
	@Column(name="NODE_LEVEL",comment="节点等级",length=1L,type=java.sql.Types.INTEGER,nullable=true)
	private Integer nodeLevel;
	
	/**
	 * jdbcType:DECIMAL
	 */
	@Column(name="IS_LEAF",comment="是否叶子节点",length=1L,type=java.sql.Types.INTEGER,nullable=true)
	private Integer isLeaf;
	
	/**
	 * jdbcType:DECIMAL
	 */
	@Column(name="SHOW_INDEX",comment="显示顺序",length=8L,defaultValue="1",type=java.sql.Types.INTEGER,nullable=false)
	private Integer showIndex;
	
	/**
	 * jdbcType:VARCHAR
	 */
	@Column(name="CREATE_BY",comment="创建人",length=22L,type=java.sql.Types.VARCHAR,nullable=false)
	private String createBy;
	
	/**
	 * jdbcType:DATETIME
	 */
	@Column(name="CREATE_TIME",comment="创建时间",length=19L,type=java.sql.Types.DATE,nullable=false)
	private LocalDateTime createTime;
	
	/**
	 * jdbcType:VARCHAR
	 */
	@Column(name="UPDATE_BY",comment="最后修改人",length=22L,type=java.sql.Types.VARCHAR,nullable=false)
	private String updateBy;
	
	/**
	 * jdbcType:DATETIME
	 */
	@Column(name="UPDATE_TIME",comment="最后修改时间",length=19L,type=java.sql.Types.DATE,nullable=false)
	private LocalDateTime updateTime;
	
	/**
	 * jdbcType:DECIMAL
	 */
	@Column(name="STATUS",comment="状态",length=1L,defaultValue="1",type=java.sql.Types.INTEGER,nullable=false)
	private Integer status;
	
	/** default constructor */
	public OrganInfo() {
	}
	
	/** pk constructor */
	public OrganInfo(String organId)
	{
		this.organId=organId;
	}
/*---end-auto-generate-don't-update-this-area--*/
}
