/**
 *@Generated by sagacity-quickvo 4.16
 */
package com.strict.modules.system.entity;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;

import com.strict.modules.system.entity.base.AbstractOrganInfo;

/**
 * @project sqltoy-strict
 * @author zhongxuchen
 * @version 1.0.0
 * Table: sys_organ_info,Remark:机构信息表 	
 */
@SqlToyEntity
public class OrganInfo extends AbstractOrganInfo {	
	/**
	 * 
	 */
	private static final long serialVersionUID = 484724793842815100L;
	
	/** default constructor */
	public OrganInfo() {
		super();
	}
	
	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public OrganInfo(String organId)
	{
		this.organId=organId;
	}

	/*---end-constructor-area---don't-update-this-area--*/

	/**
     * @todo vo columns to String
     */
    @Override
	public String toString() {
		return super.toString();
	}
	
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	@Override
	public OrganInfo clone() {
		try {
			return (OrganInfo) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}
	
}
