/**
 *@Generated by sagacity-quickvo 5.0
 */
package com.strict.modules.system.entity;

import java.io.Serializable;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;
import org.sagacity.sqltoy.config.annotation.Column;
import lombok.Data;
import lombok.experimental.Accessors;
import java.time.LocalDate;
import java.sql.Blob;
import java.time.LocalDateTime;

/**
 * @project sqltoy-strict
 * @version 1.0.0
 * Table: sys_staff_info,Remark:员工信息表  
 */
@Data
@Accessors(chain = true)
@Entity(tableName="sys_staff_info",pk_constraint="PRIMARY")
public class StaffInfo implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 2999016276055969132L;
/*---begin-auto-generate-don't-update-this-area--*/	
	/**
	 * jdbcType:VARCHAR
	 * 员工ID
	 */
	@Id(strategy="generator",generator="org.sagacity.sqltoy.plugins.id.impl.DefaultIdGenerator")
	@Column(name="STAFF_ID",length=22L,type=java.sql.Types.VARCHAR,nullable=false)
	private String staffId;
	
	/**
	 * jdbcType:VARCHAR
	 * 工号
	 */
	@Column(name="STAFF_CODE",length=22L,type=java.sql.Types.VARCHAR,nullable=false)
	private String staffCode;
	
	/**
	 * jdbcType:VARCHAR
	 * 姓名
	 */
	@Column(name="STAFF_NAME",length=30L,type=java.sql.Types.VARCHAR,nullable=false)
	private String staffName;
	
	/**
	 * jdbcType:VARCHAR
	 * 部门
	 */
	@Column(name="ORGAN_ID",length=22L,type=java.sql.Types.VARCHAR,nullable=false)
	private String organId;
	
	/**
	 * jdbcType:CHAR
	 * 性别
	 */
	@Column(name="SEX_TYPE",length=1L,type=java.sql.Types.CHAR,nullable=false)
	private String sexType;
	
	/**
	 * jdbcType:DATE
	 * 出生日期
	 */
	@Column(name="BIRTHDAY",length=10L,type=java.sql.Types.DATE,nullable=true)
	private LocalDate birthday;
	
	/**
	 * jdbcType:DATE
	 * 入职日期
	 */
	@Column(name="ENTRY_DATE",length=10L,type=java.sql.Types.DATE,nullable=false)
	private LocalDate entryDate;
	
	/**
	 * jdbcType:DATE
	 * 离职日期
	 */
	@Column(name="TERM_DATE",length=10L,type=java.sql.Types.DATE,nullable=true)
	private LocalDate termDate;
	
	/**
	 * jdbcType:LONGBLOB
	 * 照片
	 */
	@Column(name="PHOTO",length=2147483647L,type=java.sql.Types.BLOB,nullable=true)
	private byte[] photo;
	
	/**
	 * jdbcType:VARCHAR
	 * 国家
	 */
	@Column(name="COUNTRY",length=10L,type=java.sql.Types.VARCHAR,nullable=true)
	private String country;
	
	/**
	 * jdbcType:VARCHAR
	 * 籍贯
	 */
	@Column(name="CENSUS_REGISTER",length=150L,type=java.sql.Types.VARCHAR,nullable=true)
	private String censusRegister;
	
	/**
	 * jdbcType:VARCHAR
	 * 家庭地址
	 */
	@Column(name="ADDRESS",length=250L,type=java.sql.Types.VARCHAR,nullable=true)
	private String address;
	
	/**
	 * jdbcType:VARCHAR
	 * 邮箱
	 */
	@Column(name="EMAIL",length=100L,type=java.sql.Types.VARCHAR,nullable=true)
	private String email;
	
	/**
	 * jdbcType:VARCHAR
	 * 移动电话
	 */
	@Column(name="TEL_NO",length=20L,type=java.sql.Types.VARCHAR,nullable=true)
	private String telNo;
	
	/**
	 * jdbcType:VARCHAR
	 * 岗位
	 */
	@Column(name="POST",length=20L,type=java.sql.Types.VARCHAR,nullable=true)
	private String post;
	
	/**
	 * jdbcType:VARCHAR
	 * 职位级别
	 */
	@Column(name="POST_GRADE",length=20L,type=java.sql.Types.VARCHAR,nullable=true)
	private String postGrade;
	
	/**
	 * jdbcType:VARCHAR
	 * 创建人
	 */
	@Column(name="CREATE_BY",length=22L,type=java.sql.Types.VARCHAR,nullable=false)
	private String createBy;
	
	/**
	 * jdbcType:DATETIME
	 * 创建时间
	 */
	@Column(name="CREATE_TIME",length=19L,type=java.sql.Types.DATE,nullable=false)
	private LocalDateTime createTime;
	
	/**
	 * jdbcType:VARCHAR
	 * 最后修改人
	 */
	@Column(name="UPDATE_BY",length=22L,type=java.sql.Types.VARCHAR,nullable=false)
	private String updateBy;
	
	/**
	 * jdbcType:DATETIME
	 * 最后修改时间
	 */
	@Column(name="UPDATE_TIME",length=19L,type=java.sql.Types.DATE,nullable=false)
	private LocalDateTime updateTime;
	
	/**
	 * jdbcType:DECIMAL
	 * 状态
	 */
	@Column(name="STATUS",length=1L,defaultValue="1",type=java.sql.Types.INTEGER,nullable=false)
	private Integer status;
	
	/** default constructor */
	public StaffInfo() {
	}
	
	/** pk constructor */
	public StaffInfo(String staffId)
	{
		this.staffId=staffId;
	}
/*---end-auto-generate-don't-update-this-area--*/
}
