/**
 *@Generated by sagacity-quickvo 4.16
 */
package com.strict.modules.system.entity;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;

import com.strict.modules.system.entity.base.AbstractStaffInfo;

/**
 * @project sqltoy-strict
 * @author zhongxuchen
 * @version 1.0.0
 * Table: sys_staff_info,Remark:员工信息表 	
 */
@SqlToyEntity
public class StaffInfo extends AbstractStaffInfo {	
	/**
	 * 
	 */
	private static final long serialVersionUID = 2999016276055969132L;
	
	/** default constructor */
	public StaffInfo() {
		super();
	}
	
	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public StaffInfo(String staffId)
	{
		this.staffId=staffId;
	}

	/*---end-constructor-area---don't-update-this-area--*/

	/**
     * @todo vo columns to String
     */
    @Override
	public String toString() {
		return super.toString();
	}
	
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	@Override
	public StaffInfo clone() {
		try {
			return (StaffInfo) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}
	
}
