/**
 *@Generated by sagacity-quickvo 5.0
 */
package com.strict.modules.system.entity;

import java.io.Serializable;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;
import org.sagacity.sqltoy.config.annotation.Column;
import lombok.Data;
import lombok.experimental.Accessors;
import java.time.LocalDate;
import java.sql.Blob;
import java.time.LocalDateTime;

/**
 * @project sqltoy-strict
 * @version 1.0.0
 * Table: sys_staff_info,Remark:员工信息表  
 */
@Data
@Accessors(chain = true)
@Entity(tableName="sys_staff_info",pk_constraint="PRIMARY")
public class StaffInfo implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 2999016276055969132L;
/*---begin-auto-generate-don't-update-this-area--*/	
	/**
	 * jdbcType:VARCHAR
	 */
	@Id(strategy="generator",generator="org.sagacity.sqltoy.plugins.id.impl.DefaultIdGenerator")
	@Column(name="STAFF_ID",comment="员工ID",length=22L,type=java.sql.Types.VARCHAR,nullable=false)
	private String staffId;
	
	/**
	 * jdbcType:VARCHAR
	 */
	@Column(name="STAFF_CODE",comment="工号",length=22L,type=java.sql.Types.VARCHAR,nullable=false)
	private String staffCode;
	
	/**
	 * jdbcType:VARCHAR
	 */
	@Column(name="STAFF_NAME",comment="姓名",length=30L,type=java.sql.Types.VARCHAR,nullable=false)
	private String staffName;
	
	/**
	 * jdbcType:VARCHAR
	 */
	@Column(name="ORGAN_ID",comment="部门",length=22L,type=java.sql.Types.VARCHAR,nullable=false)
	private String organId;
	
	/**
	 * jdbcType:CHAR
	 */
	@Column(name="SEX_TYPE",comment="性别",length=1L,type=java.sql.Types.CHAR,nullable=false)
	private String sexType;
	
	/**
	 * jdbcType:DATE
	 */
	@Column(name="BIRTHDAY",comment="出生日期",length=10L,type=java.sql.Types.DATE,nullable=true)
	private LocalDate birthday;
	
	/**
	 * jdbcType:DATE
	 */
	@Column(name="ENTRY_DATE",comment="入职日期",length=10L,type=java.sql.Types.DATE,nullable=false)
	private LocalDate entryDate;
	
	/**
	 * jdbcType:DATE
	 */
	@Column(name="TERM_DATE",comment="离职日期",length=10L,type=java.sql.Types.DATE,nullable=true)
	private LocalDate termDate;
	
	/**
	 * jdbcType:LONGBLOB
	 */
	@Column(name="PHOTO",comment="照片",length=2147483647L,type=java.sql.Types.BLOB,nullable=true)
	private byte[] photo;
	
	/**
	 * jdbcType:VARCHAR
	 */
	@Column(name="COUNTRY",comment="国家",length=10L,type=java.sql.Types.VARCHAR,nullable=true)
	private String country;
	
	/**
	 * jdbcType:VARCHAR
	 */
	@Column(name="CENSUS_REGISTER",comment="籍贯",length=150L,type=java.sql.Types.VARCHAR,nullable=true)
	private String censusRegister;
	
	/**
	 * jdbcType:VARCHAR
	 */
	@Column(name="ADDRESS",comment="家庭地址",length=250L,type=java.sql.Types.VARCHAR,nullable=true)
	private String address;
	
	/**
	 * jdbcType:VARCHAR
	 */
	@Column(name="EMAIL",comment="邮箱",length=100L,type=java.sql.Types.VARCHAR,nullable=true)
	private String email;
	
	/**
	 * jdbcType:VARCHAR
	 */
	@Column(name="TEL_NO",comment="移动电话",length=20L,type=java.sql.Types.VARCHAR,nullable=true)
	private String telNo;
	
	/**
	 * jdbcType:VARCHAR
	 */
	@Column(name="POST",comment="岗位",length=20L,type=java.sql.Types.VARCHAR,nullable=true)
	private String post;
	
	/**
	 * jdbcType:VARCHAR
	 */
	@Column(name="POST_GRADE",comment="职位级别",length=20L,type=java.sql.Types.VARCHAR,nullable=true)
	private String postGrade;
	
	/**
	 * jdbcType:VARCHAR
	 */
	@Column(name="CREATE_BY",comment="创建人",length=22L,type=java.sql.Types.VARCHAR,nullable=false)
	private String createBy;
	
	/**
	 * jdbcType:DATETIME
	 */
	@Column(name="CREATE_TIME",comment="创建时间",length=19L,type=java.sql.Types.DATE,nullable=false)
	private LocalDateTime createTime;
	
	/**
	 * jdbcType:VARCHAR
	 */
	@Column(name="UPDATE_BY",comment="最后修改人",length=22L,type=java.sql.Types.VARCHAR,nullable=false)
	private String updateBy;
	
	/**
	 * jdbcType:DATETIME
	 */
	@Column(name="UPDATE_TIME",comment="最后修改时间",length=19L,type=java.sql.Types.DATE,nullable=false)
	private LocalDateTime updateTime;
	
	/**
	 * jdbcType:DECIMAL
	 */
	@Column(name="STATUS",comment="状态",length=1L,defaultValue="1",type=java.sql.Types.INTEGER,nullable=false)
	private Integer status;
	
	/** default constructor */
	public StaffInfo() {
	}
	
	/** pk constructor */
	public StaffInfo(String staffId)
	{
		this.staffId=staffId;
	}
/*---end-auto-generate-don't-update-this-area--*/
}
