/**
 *@Generated by sagacity-quickvo 4.16
 */
package com.strict.modules.system.vo;

import java.io.Serializable;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDateTime;

/**
 * @project sqltoy-strict
 * @version 1.0.0
 * ,Remark:机构信息表  
 */
@ApiModel(value="OrganInfoVO",description="机构信息表")
public class OrganInfoVO implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 484724793842815100L;
	
/*---begin-auto-generate-don't-update-this-area--*/	
	/**
	 * 机构ID
	 */
	@ApiModelProperty(value="机构ID",allowEmptyValue=false)
	private String organId;
	
	/**
	 * 机构名称
	 */
	@ApiModelProperty(value="机构名称",allowEmptyValue=false)
	private String organName;
	
	/**
	 * 机构代码
	 */
	@ApiModelProperty(value="机构代码",allowEmptyValue=false)
	private String organCode;
	
	/**
	 * 成本中心代码
	 */
	@ApiModelProperty(value="成本中心代码",allowEmptyValue=true)
	private String costNo;
	
	/**
	 * 父机构ID
	 */
	@ApiModelProperty(value="父机构ID",allowEmptyValue=false)
	private String organPid;
	
	/**
	 * 节点路径
	 */
	@ApiModelProperty(value="节点路径",allowEmptyValue=true)
	private String nodeRoute;
	
	/**
	 * 节点等级
	 */
	@ApiModelProperty(value="节点等级",allowEmptyValue=true)
	private Integer nodeLevel;
	
	/**
	 * 是否叶子节点
	 */
	@ApiModelProperty(value="是否叶子节点",allowEmptyValue=true)
	private Integer isLeaf;
	
	/**
	 * 显示顺序
	 */
	@ApiModelProperty(value="显示顺序",allowEmptyValue=false)
	private Integer showIndex;
	
	/**
	 * 创建人
	 */
	@ApiModelProperty(value="创建人",allowEmptyValue=false)
	private String createBy;
	
	/**
	 * 创建时间
	 */
	@ApiModelProperty(value="创建时间",allowEmptyValue=false)
	private LocalDateTime createTime;
	
	/**
	 * 最后修改人
	 */
	@ApiModelProperty(value="最后修改人",allowEmptyValue=false)
	private String updateBy;
	
	/**
	 * 最后修改时间
	 */
	@ApiModelProperty(value="最后修改时间",allowEmptyValue=false)
	private LocalDateTime updateTime;
	
	/**
	 * 状态
	 */
	@ApiModelProperty(value="状态",allowEmptyValue=false)
	private Integer status;
	
	
	/**
	 *@param organId the organId to set
	 */
	public OrganInfoVO setOrganId(String organId) {
		this.organId=organId;
		return this;
	}
		
	/**
	 *@return the OrganId
	 */
	public String getOrganId() {
	    return this.organId;
	}
	
	/**
	 *@param organName the organName to set
	 */
	public OrganInfoVO setOrganName(String organName) {
		this.organName=organName;
		return this;
	}
		
	/**
	 *@return the OrganName
	 */
	public String getOrganName() {
	    return this.organName;
	}
	
	/**
	 *@param organCode the organCode to set
	 */
	public OrganInfoVO setOrganCode(String organCode) {
		this.organCode=organCode;
		return this;
	}
		
	/**
	 *@return the OrganCode
	 */
	public String getOrganCode() {
	    return this.organCode;
	}
	
	/**
	 *@param costNo the costNo to set
	 */
	public OrganInfoVO setCostNo(String costNo) {
		this.costNo=costNo;
		return this;
	}
		
	/**
	 *@return the CostNo
	 */
	public String getCostNo() {
	    return this.costNo;
	}
	
	/**
	 *@param organPid the organPid to set
	 */
	public OrganInfoVO setOrganPid(String organPid) {
		this.organPid=organPid;
		return this;
	}
		
	/**
	 *@return the OrganPid
	 */
	public String getOrganPid() {
	    return this.organPid;
	}
	
	/**
	 *@param nodeRoute the nodeRoute to set
	 */
	public OrganInfoVO setNodeRoute(String nodeRoute) {
		this.nodeRoute=nodeRoute;
		return this;
	}
		
	/**
	 *@return the NodeRoute
	 */
	public String getNodeRoute() {
	    return this.nodeRoute;
	}
	
	/**
	 *@param nodeLevel the nodeLevel to set
	 */
	public OrganInfoVO setNodeLevel(Integer nodeLevel) {
		this.nodeLevel=nodeLevel;
		return this;
	}
		
	/**
	 *@return the NodeLevel
	 */
	public Integer getNodeLevel() {
	    return this.nodeLevel;
	}
	
	/**
	 *@param isLeaf the isLeaf to set
	 */
	public OrganInfoVO setIsLeaf(Integer isLeaf) {
		this.isLeaf=isLeaf;
		return this;
	}
		
	/**
	 *@return the IsLeaf
	 */
	public Integer getIsLeaf() {
	    return this.isLeaf;
	}
	
	/**
	 *@param showIndex the showIndex to set
	 */
	public OrganInfoVO setShowIndex(Integer showIndex) {
		this.showIndex=showIndex;
		return this;
	}
		
	/**
	 *@return the ShowIndex
	 */
	public Integer getShowIndex() {
	    return this.showIndex;
	}
	
	/**
	 *@param createBy the createBy to set
	 */
	public OrganInfoVO setCreateBy(String createBy) {
		this.createBy=createBy;
		return this;
	}
		
	/**
	 *@return the CreateBy
	 */
	public String getCreateBy() {
	    return this.createBy;
	}
	
	/**
	 *@param createTime the createTime to set
	 */
	public OrganInfoVO setCreateTime(LocalDateTime createTime) {
		this.createTime=createTime;
		return this;
	}
		
	/**
	 *@return the CreateTime
	 */
	public LocalDateTime getCreateTime() {
	    return this.createTime;
	}
	
	/**
	 *@param updateBy the updateBy to set
	 */
	public OrganInfoVO setUpdateBy(String updateBy) {
		this.updateBy=updateBy;
		return this;
	}
		
	/**
	 *@return the UpdateBy
	 */
	public String getUpdateBy() {
	    return this.updateBy;
	}
	
	/**
	 *@param updateTime the updateTime to set
	 */
	public OrganInfoVO setUpdateTime(LocalDateTime updateTime) {
		this.updateTime=updateTime;
		return this;
	}
		
	/**
	 *@return the UpdateTime
	 */
	public LocalDateTime getUpdateTime() {
	    return this.updateTime;
	}
	
	/**
	 *@param status the status to set
	 */
	public OrganInfoVO setStatus(Integer status) {
		this.status=status;
		return this;
	}
		
	/**
	 *@return the Status
	 */
	public Integer getStatus() {
	    return this.status;
	}
/*---end-auto-generate-don't-update-this-area--*/	
}
