/**
 *@Generated by sagacity-quickvo 5.0
 */
package com.strict.modules.system.vo;

import java.io.Serializable;
import lombok.Data;
import lombok.experimental.Accessors;
import java.time.LocalDateTime;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * @project sqltoy-strict
 * @version 1.0.0
 * @description sys_organ_info,机构信息表  
 */
@Schema(name="OrganInfoVO",description="机构信息表")
@Data
@Accessors(chain = true)
public class OrganInfoVO implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 3877868311872767134L;
	
/*---begin-auto-generate-don't-update-this-area--*/	
	/**
	 * 机构ID
	 */
	@Schema(name="organId",description="机构ID",nullable=false)
	private String organId;
	
	/**
	 * 机构名称
	 */
	@Schema(name="organName",description="机构名称",nullable=false)
	private String organName;
	
	/**
	 * 机构代码
	 */
	@Schema(name="organCode",description="机构代码",nullable=false)
	private String organCode;
	
	/**
	 * 成本中心代码
	 */
	@Schema(name="costNo",description="成本中心代码",nullable=true)
	private String costNo;
	
	/**
	 * 父机构ID
	 */
	@Schema(name="organPid",description="父机构ID",nullable=false)
	private String organPid;
	
	/**
	 * 节点路径
	 */
	@Schema(name="nodeRoute",description="节点路径",nullable=true)
	private String nodeRoute;
	
	/**
	 * 节点等级
	 */
	@Schema(name="nodeLevel",description="节点等级",nullable=true)
	private Integer nodeLevel;
	
	/**
	 * 是否叶子节点
	 */
	@Schema(name="isLeaf",description="是否叶子节点",nullable=true)
	private Integer isLeaf;
	
	/**
	 * 显示顺序
	 */
	@Schema(name="showIndex",description="显示顺序",nullable=false)
	private Integer showIndex;
	
	/**
	 * 创建人
	 */
	@Schema(name="createBy",description="创建人",nullable=false)
	private String createBy;
	
	/**
	 * 创建时间
	 */
	@Schema(name="createTime",description="创建时间",nullable=false)
	private LocalDateTime createTime;
	
	/**
	 * 最后修改人
	 */
	@Schema(name="updateBy",description="最后修改人",nullable=false)
	private String updateBy;
	
	/**
	 * 最后修改时间
	 */
	@Schema(name="updateTime",description="最后修改时间",nullable=false)
	private LocalDateTime updateTime;
	
	/**
	 * 状态
	 */
	@Schema(name="status",description="状态",nullable=false)
	private Integer status;
	
/*---end-auto-generate-don't-update-this-area--*/	
}
