/**
 *@Generated by sagacity-quickvo 4.16
 */
package com.strict.modules.system.vo;

import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * @project sqltoy-strict
 * @version 1.0.0 ,Remark:员工信息表
 */
@ApiModel(value = "StaffInfoVO", description = "员工信息表")
public class StaffInfoVO implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2999016276055969132L;

	/**
	 * 机构名称
	 */
	private String organName;

	/**
	 * @return the organName
	 */
	public String getOrganName() {
		return organName;
	}

	/**
	 * @param organName the organName to set
	 */
	public void setOrganName(String organName) {
		this.organName = organName;
	}

	/*---begin-auto-generate-don't-update-this-area--*/	
   /**
	 * 员工ID
	 */
	@ApiModelProperty(name="STAFF_ID",value="员工ID",allowEmptyValue=false)
	private String staffId;
	
   /**
	 * 工号
	 */
	@ApiModelProperty(name="STAFF_CODE",value="工号",allowEmptyValue=false)
	private String staffCode;
	
   /**
	 * 姓名
	 */
	@ApiModelProperty(name="STAFF_NAME",value="姓名",allowEmptyValue=false)
	private String staffName;
	
   /**
	 * 部门
	 */
	@ApiModelProperty(name="ORGAN_ID",value="部门",allowEmptyValue=false)
	private String organId;
	
   /**
	 * 性别
	 */
	@ApiModelProperty(name="SEX_TYPE",value="性别",allowEmptyValue=false)
	private String sexType;
	
   /**
	 * 出生日期
	 */
	@ApiModelProperty(name="BIRTHDAY",value="出生日期",allowEmptyValue=true)
	private LocalDate birthday;
	
   /**
	 * 入职日期
	 */
	@ApiModelProperty(name="ENTRY_DATE",value="入职日期",allowEmptyValue=false)
	private LocalDate entryDate;
	
   /**
	 * 离职日期
	 */
	@ApiModelProperty(name="TERM_DATE",value="离职日期",allowEmptyValue=true)
	private LocalDate termDate;
	
   /**
	 * 照片
	 */
	@ApiModelProperty(name="PHOTO",value="照片",allowEmptyValue=true)
	private byte[] photo;
	
   /**
	 * 国家
	 */
	@ApiModelProperty(name="COUNTRY",value="国家",allowEmptyValue=true)
	private String country;
	
   /**
	 * 籍贯
	 */
	@ApiModelProperty(name="CENSUS_REGISTER",value="籍贯",allowEmptyValue=true)
	private String censusRegister;
	
   /**
	 * 家庭地址
	 */
	@ApiModelProperty(name="ADDRESS",value="家庭地址",allowEmptyValue=true)
	private String address;
	
   /**
	 * 邮箱
	 */
	@ApiModelProperty(name="EMAIL",value="邮箱",allowEmptyValue=true)
	private String email;
	
   /**
	 * 移动电话
	 */
	@ApiModelProperty(name="TEL_NO",value="移动电话",allowEmptyValue=true)
	private String telNo;
	
   /**
	 * 岗位
	 */
	@ApiModelProperty(name="POST",value="岗位",allowEmptyValue=true)
	private String post;
	
   /**
	 * 职位级别
	 */
	@ApiModelProperty(name="POST_GRADE",value="职位级别",allowEmptyValue=true)
	private String postGrade;
	
   /**
	 * 创建人
	 */
	@ApiModelProperty(name="CREATE_BY",value="创建人",allowEmptyValue=false)
	private String createBy;
	
   /**
	 * 创建时间
	 */
	@ApiModelProperty(name="CREATE_TIME",value="创建时间",allowEmptyValue=false)
	private LocalDateTime createTime;
	
   /**
	 * 最后修改人
	 */
	@ApiModelProperty(name="UPDATE_BY",value="最后修改人",allowEmptyValue=false)
	private String updateBy;
	
   /**
	 * 最后修改时间
	 */
	@ApiModelProperty(name="UPDATE_TIME",value="最后修改时间",allowEmptyValue=false)
	private LocalDateTime updateTime;
	
   /**
	 * 状态
	 */
	@ApiModelProperty(name="STATUS",value="状态",allowEmptyValue=false)
	private Integer status;
	
	
	/**
	 *@param staffId the staffId to set
	 */
	public StaffInfoVO setStaffId(String staffId) {
		this.staffId=staffId;
		return this;
	}
		
	/**
	 *@return the StaffId
	 */
	public String getStaffId() {
	    return this.staffId;
	}
	
	/**
	 *@param staffCode the staffCode to set
	 */
	public StaffInfoVO setStaffCode(String staffCode) {
		this.staffCode=staffCode;
		return this;
	}
		
	/**
	 *@return the StaffCode
	 */
	public String getStaffCode() {
	    return this.staffCode;
	}
	
	/**
	 *@param staffName the staffName to set
	 */
	public StaffInfoVO setStaffName(String staffName) {
		this.staffName=staffName;
		return this;
	}
		
	/**
	 *@return the StaffName
	 */
	public String getStaffName() {
	    return this.staffName;
	}
	
	/**
	 *@param organId the organId to set
	 */
	public StaffInfoVO setOrganId(String organId) {
		this.organId=organId;
		return this;
	}
		
	/**
	 *@return the OrganId
	 */
	public String getOrganId() {
	    return this.organId;
	}
	
	/**
	 *@param sexType the sexType to set
	 */
	public StaffInfoVO setSexType(String sexType) {
		this.sexType=sexType;
		return this;
	}
		
	/**
	 *@return the SexType
	 */
	public String getSexType() {
	    return this.sexType;
	}
	
	/**
	 *@param birthday the birthday to set
	 */
	public StaffInfoVO setBirthday(LocalDate birthday) {
		this.birthday=birthday;
		return this;
	}
		
	/**
	 *@return the Birthday
	 */
	public LocalDate getBirthday() {
	    return this.birthday;
	}
	
	/**
	 *@param entryDate the entryDate to set
	 */
	public StaffInfoVO setEntryDate(LocalDate entryDate) {
		this.entryDate=entryDate;
		return this;
	}
		
	/**
	 *@return the EntryDate
	 */
	public LocalDate getEntryDate() {
	    return this.entryDate;
	}
	
	/**
	 *@param termDate the termDate to set
	 */
	public StaffInfoVO setTermDate(LocalDate termDate) {
		this.termDate=termDate;
		return this;
	}
		
	/**
	 *@return the TermDate
	 */
	public LocalDate getTermDate() {
	    return this.termDate;
	}
	
	/**
	 *@param photo the photo to set
	 */
	public StaffInfoVO setPhoto(byte[] photo) {
		this.photo=photo;
		return this;
	}
		
	/**
	 *@return the Photo
	 */
	public byte[] getPhoto() {
	    return this.photo;
	}
	
	/**
	 *@param country the country to set
	 */
	public StaffInfoVO setCountry(String country) {
		this.country=country;
		return this;
	}
		
	/**
	 *@return the Country
	 */
	public String getCountry() {
	    return this.country;
	}
	
	/**
	 *@param censusRegister the censusRegister to set
	 */
	public StaffInfoVO setCensusRegister(String censusRegister) {
		this.censusRegister=censusRegister;
		return this;
	}
		
	/**
	 *@return the CensusRegister
	 */
	public String getCensusRegister() {
	    return this.censusRegister;
	}
	
	/**
	 *@param address the address to set
	 */
	public StaffInfoVO setAddress(String address) {
		this.address=address;
		return this;
	}
		
	/**
	 *@return the Address
	 */
	public String getAddress() {
	    return this.address;
	}
	
	/**
	 *@param email the email to set
	 */
	public StaffInfoVO setEmail(String email) {
		this.email=email;
		return this;
	}
		
	/**
	 *@return the Email
	 */
	public String getEmail() {
	    return this.email;
	}
	
	/**
	 *@param telNo the telNo to set
	 */
	public StaffInfoVO setTelNo(String telNo) {
		this.telNo=telNo;
		return this;
	}
		
	/**
	 *@return the TelNo
	 */
	public String getTelNo() {
	    return this.telNo;
	}
	
	/**
	 *@param post the post to set
	 */
	public StaffInfoVO setPost(String post) {
		this.post=post;
		return this;
	}
		
	/**
	 *@return the Post
	 */
	public String getPost() {
	    return this.post;
	}
	
	/**
	 *@param postGrade the postGrade to set
	 */
	public StaffInfoVO setPostGrade(String postGrade) {
		this.postGrade=postGrade;
		return this;
	}
		
	/**
	 *@return the PostGrade
	 */
	public String getPostGrade() {
	    return this.postGrade;
	}
	
	/**
	 *@param createBy the createBy to set
	 */
	public StaffInfoVO setCreateBy(String createBy) {
		this.createBy=createBy;
		return this;
	}
		
	/**
	 *@return the CreateBy
	 */
	public String getCreateBy() {
	    return this.createBy;
	}
	
	/**
	 *@param createTime the createTime to set
	 */
	public StaffInfoVO setCreateTime(LocalDateTime createTime) {
		this.createTime=createTime;
		return this;
	}
		
	/**
	 *@return the CreateTime
	 */
	public LocalDateTime getCreateTime() {
	    return this.createTime;
	}
	
	/**
	 *@param updateBy the updateBy to set
	 */
	public StaffInfoVO setUpdateBy(String updateBy) {
		this.updateBy=updateBy;
		return this;
	}
		
	/**
	 *@return the UpdateBy
	 */
	public String getUpdateBy() {
	    return this.updateBy;
	}
	
	/**
	 *@param updateTime the updateTime to set
	 */
	public StaffInfoVO setUpdateTime(LocalDateTime updateTime) {
		this.updateTime=updateTime;
		return this;
	}
		
	/**
	 *@return the UpdateTime
	 */
	public LocalDateTime getUpdateTime() {
	    return this.updateTime;
	}
	
	/**
	 *@param status the status to set
	 */
	public StaffInfoVO setStatus(Integer status) {
		this.status=status;
		return this;
	}
		
	/**
	 *@return the Status
	 */
	public Integer getStatus() {
	    return this.status;
	}
/*---end-auto-generate-don't-update-this-area--*/
}
