/**
 *@Generated by sagacity-quickvo 5.0
 */
package com.strict.modules.sagacity.entity;

import java.io.Serializable;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;
import org.sagacity.sqltoy.config.annotation.Column;
import lombok.Data;
import lombok.experimental.Accessors;
import java.time.LocalDateTime;

/**
 * @project sqltoy-strict
 * @version 1.0.0
 * Table: sag_dict_detail,Remark:字典明细表  
 */
@Data
@Accessors(chain = true)
@Entity(tableName="sag_dict_detail",pk_constraint="PRIMARY")
public class DictDetail implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 8137101015349347912L;
/*---begin-auto-generate-don't-update-this-area--*/	
	/**
	 * jdbcType:VARCHAR
	 * 字典KEY
	 */
	@Id
	@Column(name="DICT_KEY",length=50L,type=java.sql.Types.VARCHAR,nullable=false)
	private String dictKey;
	
	/**
	 * jdbcType:VARCHAR
	 * 字典类型代码
	 */
	@Id
	@Column(name="DICT_TYPE",length=50L,type=java.sql.Types.VARCHAR,nullable=false)
	private String dictType;
	
	/**
	 * jdbcType:VARCHAR
	 * 字典值
	 */
	@Column(name="DICT_NAME",length=200L,type=java.sql.Types.VARCHAR,nullable=false)
	private String dictName;
	
	/**
	 * jdbcType:DECIMAL
	 * 显示顺序
	 */
	@Column(name="SHOW_INDEX",length=8L,defaultValue="1",type=java.sql.Types.INTEGER,nullable=false)
	private Integer showIndex;
	
	/**
	 * jdbcType:VARCHAR
	 * 最后修改人
	 */
	@Column(name="UPDATE_BY",length=22L,type=java.sql.Types.VARCHAR,nullable=false)
	private String updateBy;
	
	/**
	 * jdbcType:DATETIME
	 * 最后修改时间
	 */
	@Column(name="UPDATE_TIME",length=19L,type=java.sql.Types.DATE,nullable=false)
	private LocalDateTime updateTime;
	
	/**
	 * jdbcType:DECIMAL
	 * 状态
	 */
	@Column(name="STATUS",length=1L,defaultValue="1",type=java.sql.Types.INTEGER,nullable=false)
	private Integer status;
	
	/** default constructor */
	public DictDetail() {
	}
	
	/** pk constructor */
	public DictDetail(String dictKey,String dictType)
	{
		this.dictKey=dictKey;
		this.dictType=dictType;
	}
/*---end-auto-generate-don't-update-this-area--*/
	/**
	 * 在实体类中扩展一个附加属性
	 */
	private String dictTypeName;
}
