/**
 *@Generated by sagacity-quickvo 4.16
 */
package com.strict.modules.sagacity.entity;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;

import com.strict.modules.sagacity.entity.base.AbstractDictDetail;

/**
 * @project sqltoy-strict
 * @author zhongxuchen
 * @version 1.0.0
 * Table: sag_dict_detail,Remark:字典明细表 	
 */
@SqlToyEntity
public class DictDetail extends AbstractDictDetail {	
	/**
	 * 
	 */
	private static final long serialVersionUID = 8137101015349347912L;
	
	/** default constructor */
	public DictDetail() {
		super();
	}
	
	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public DictDetail(String dictKey,String dictType)
	{
		this.dictKey=dictKey;
		this.dictType=dictType;
	}

	/*---end-constructor-area---don't-update-this-area--*/

	/**
     * @todo vo columns to String
     */
    @Override
	public String toString() {
		return super.toString();
	}
	
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	@Override
	public DictDetail clone() {
		try {
			return (DictDetail) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}
	
}
