/**
 *@Generated by sagacity-quickvo 5.0
 */
package com.strict.modules.sagacity.entity;

import java.io.Serializable;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;
import org.sagacity.sqltoy.config.annotation.Column;
import lombok.Data;
import lombok.experimental.Accessors;
import java.time.LocalDateTime;
import org.sagacity.sqltoy.config.annotation.OneToMany;
import java.util.ArrayList;
import java.util.List;

/**
 * @project sqltoy-strict
 * @version 1.0.0
 * Table: sag_dict_type,Remark:字典分类表  
 */
@Data
@Accessors(chain = true)
@Entity(tableName="sag_dict_type",pk_constraint="PRIMARY")
public class DictType implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 426724547793495250L;
/*---begin-auto-generate-don't-update-this-area--*/	
	/**
	 * jdbcType:VARCHAR
	 * 字典类型代码
	 */
	@Id(strategy="generator",generator="org.sagacity.sqltoy.plugins.id.impl.DefaultIdGenerator")
	@Column(name="DICT_TYPE",length=50L,type=java.sql.Types.VARCHAR,nullable=false)
	private String dictType;
	
	/**
	 * jdbcType:VARCHAR
	 * 字典类型名称
	 */
	@Column(name="DICT_TYPE_NAME",length=100L,type=java.sql.Types.VARCHAR,nullable=false)
	private String dictTypeName;
	
	/**
	 * jdbcType:VARCHAR
	 * 说明
	 */
	@Column(name="COMMENTS",length=500L,type=java.sql.Types.VARCHAR,nullable=true)
	private String comments;
	
	/**
	 * jdbcType:DECIMAL
	 * 显示顺序
	 */
	@Column(name="SHOW_INDEX",length=8L,defaultValue="1",type=java.sql.Types.INTEGER,nullable=false)
	private Integer showIndex;
	
	/**
	 * jdbcType:VARCHAR
	 * 创建人
	 */
	@Column(name="CREATE_BY",length=22L,type=java.sql.Types.VARCHAR,nullable=false)
	private String createBy;
	
	/**
	 * jdbcType:DATETIME
	 * 创建时间
	 */
	@Column(name="CREATE_TIME",length=19L,type=java.sql.Types.DATE,nullable=false)
	private LocalDateTime createTime;
	
	/**
	 * jdbcType:VARCHAR
	 * 最后修改人
	 */
	@Column(name="UPDATE_BY",length=22L,type=java.sql.Types.VARCHAR,nullable=false)
	private String updateBy;
	
	/**
	 * jdbcType:DATETIME
	 * 最后修改时间
	 */
	@Column(name="UPDATE_TIME",length=19L,type=java.sql.Types.DATE,nullable=false)
	private LocalDateTime updateTime;
	
	/**
	 * jdbcType:DECIMAL
	 * 状态
	 */
	@Column(name="STATUS",length=1L,defaultValue="1",type=java.sql.Types.INTEGER,nullable=false)
	private Integer status;
	
	/**
	 * 主键关联子表信息
	 */
	@OneToMany(fields={"dictType"},mappedFields={"dictType"},delete=true)
	private List<DictDetail> dictDetails=new ArrayList<DictDetail>();

	/** default constructor */
	public DictType() {
	}
	
	/** pk constructor */
	public DictType(String dictType)
	{
		this.dictType=dictType;
	}
/*---end-auto-generate-don't-update-this-area--*/
}
