/**
 *@Generated by sagacity-quickvo 5.0
 */
package com.strict.modules.sagacity.vo;

import java.io.Serializable;
import java.time.LocalDateTime;

import io.swagger.annotations.ApiModel;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.experimental.Accessors;

/**
 * @project sqltoy-strict
 * @version 1.0.0
 * @description sag_dict_type,字典分类表  
 */
@ApiModel(value="DictTypeVO",description="字典分类表")
@Data
@Accessors(chain = true)
public class DictTypeVO implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 5751584088649981005L;
	
/*---begin-auto-generate-don't-update-this-area--*/	
	/**
	 * 字典类型代码
	 */
	@Schema(name="dictType",description="字典类型代码",nullable=false)
	private String dictType;
	
	/**
	 * 字典类型名称
	 */
	@Schema(name="dictTypeName",description="字典类型名称",nullable=false)
	private String dictTypeName;
	
	/**
	 * 说明
	 */
	@Schema(name="comments",description="说明",nullable=true)
	private String comments;
	
	/**
	 * 显示顺序
	 */
	@Schema(name="showIndex",description="显示顺序",nullable=false)
	private Integer showIndex;
	
	/**
	 * 创建人
	 */
	@Schema(name="createBy",description="创建人",nullable=false)
	private String createBy;
	
	/**
	 * 创建时间
	 */
	@Schema(name="createTime",description="创建时间",nullable=false)
	private LocalDateTime createTime;
	
	/**
	 * 最后修改人
	 */
	@Schema(name="updateBy",description="最后修改人",nullable=false)
	private String updateBy;
	
	/**
	 * 最后修改时间
	 */
	@Schema(name="updateTime",description="最后修改时间",nullable=false)
	private LocalDateTime updateTime;
	
	/**
	 * 状态
	 */
	@Schema(name="status",description="状态",nullable=false)
	private Integer status;
	
/*---end-auto-generate-don't-update-this-area--*/	
}
